export class Property {
    constructor (
        public PropertyID: number,
        public AgentContactID: number,
        public AgentBusinessID: number,
        public MLSIdentifer : string,
        public ListingAgentName : string,
        public ListingAgentCompany : string,
        public PropertyType : string,
        public YearBuilt: number,
        public SquareFeet: number,
        public LotSize : string,
        public NumberOfBedrooms : number,
        public NumberOfBathrooms : number,
        public CurrentListPrice : number,
        public CurrentListDate : Date,
        public GeneralMarketingDescription : string,
        public LotFeatures : string,
        public InteriorFeatures : string,
        public ExteriorFeatures : string,
        public BasementDescription : string,
        public ParkingDescription : string,
        public SewerDescription : string,
        public UtilitiesDescription : string,
        public NeighborhoodDescription : string,
        public ElementarySchool : string,
        public MiddleSchool : string,
        public HighSchool : string,
        public Address1 : string,
        public Address2 : string,
        public City : string,
        public StateID : string,
        public ZipCode : string,
        public ZipCodePlusFour : string,
        public County : string,
        public Latitude : number,
        public Longitude : number,
        public IsDeleted : boolean,
        public ConcurrencyID : number,
        public CreatedDate : Date,
        public CreatedByUser : number,
        public LastUpdatedDate : Date,
        public LastUpdatedByUser : number,
        public ListingAgentPhone : string,
        public ListingAgentEmail : string,
        public ListingNumber : number,
        public GeoLocation: string
    ) { }
}